language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: "2.7"
          env: TOXENV=py27
        - os: linux
          sudo: required
          python: "3.6"
          env: TOXENV=py36
        - os: linux
          sudo: required
          python: "nightly"
          env: TOXENV=pynightly
        - os: osx
          language: generic
          env: TOXENV=py27
          before_install:
            - brew update
            - virtualenv env -p python2
            - source env/bin/activate
        - os: osx
          language: generic
          env: TOXENV=py36
          before_install:
            - brew update
            - brew install python3
            - virtualenv env -p python3
            - source env/bin/activate

install:
    - pip install .[tests]
    - pip install coveralls
    
script:
- coverage run -m unittest discover

after_success:
  - coveralls

deploy:
  provider: pypi
  user: "dwtools"
  password:
    secure: vAU0Y5yUtfu7DKr/h90ba3ZmvgWXXUREa1FC1b0G/Kpuj0SadF8wNI9nWlwSET1mcrNut+1KR2bkbkYC1lT8qLYjkUXeKe+7re3iLh5RMihQyXCQ0HwxJvltVDlgmkKI6AmSS5Vjr/JE4TQt2RfAZnkrcuiQoS1mIJ9LMdhePqgpuUbtifvvaZLw/kJ3phR0SX/Us8Dtu6BshcBCdLFnP4eGyVGVczO2fa3bozzvIMzHpJIaJ7CwBti6VkgRLwEqQ8RmZw1OBAYFqJGGCrO2giiOzCwlSYXbp12v+c3y+Oi38blYg8WXyNuw07PWZnvqB383Kmt7qDkgUFRuRsGTbPIFZEnUn2QB/xEyF78rZCOncH99MW+4oScVjOWGSNuoa7bYnPfv5551p24JJ2av6XIX9UwedwnYOL8yn9wucHY48UNORlBSaEqHPO084mvaRIE+4Q/LC1qCmgmc4VPrzx4UHgwehKGBkkkUMwW27uoTPpE4827Egdm/FtFT2cAiKqL28nL/gc4xECTjNcF/CKaJqb0Pdx0dNlF62twZvRWWQW/NvajP0hTs+m30CEyAOEUjJaqNRKMR6HKYVrTEhGTPdb/pwzmKLyTWM9jsWZ02sJRft7RRapeyeDO77QOaz/yd2yUkCcnchl3GrUUpWBd3mP3RvBiEDssgo1arcqI=
    distributions: "sdist bdist_wheel"
  skip_cleanup: true
  on:
    tags: true
